import type { SiteContent } from './types';

/** Demo content for the 4 main templates — used in Showcase preview */
export const DEMO_CONTENT: Record<string, SiteContent & Record<string, any>> = {
  restaurant: {
    brand: { name: 'Osteria al Porto', tagline: 'Italienische Küche mit Blick auf den Hafen', logoUrl: '', primaryColor: '#b91c1c', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 512 123456', email: 'info@osteria-porto.at', address: 'Hafenstraße 12', city: '6020 Innsbruck', hours: [{ day: 'Di–Sa', time: '11:30–14:00 · 17:30–22:00' }, { day: 'So', time: '11:30–15:00' }], mapsUrl: '' },
    social: { instagram: '@osteriaalporto', facebook: '', whatsapp: '+43512123456', linkedin: '', youtube: '', tiktok: '', x: '' },
    services: [
      { name: 'Bruschetta Trio', price: '€ 12', description: 'Tomate, Olive, Trüffel' },
      { name: 'Risotto ai Funghi', price: '€ 19', description: 'Steinpilze, Parmesan, Thymian' },
      { name: 'Tagliata di Manzo', price: '€ 28', description: 'Rinderfilet, Rucola, Balsamico' },
      { name: 'Spaghetti Vongole', price: '€ 22', description: 'Frische Venusmuscheln, Knoblauch' },
      { name: 'Tiramisu della Casa', price: '€ 9', description: 'Hauseigenes Rezept' },
      { name: 'Antipasto Misto', price: '€ 16', description: 'Gemischte Vorspeisen-Platte' },
    ],
    testimonials: [
      { text: 'Das beste italienische Restaurant in der Stadt. Jedes Gericht ein Gedicht.', author: 'Maria K.' },
      { text: 'Fantastische Atmosphäre und der Service ist immer aufmerksam.', author: 'Thomas W.' },
      { text: 'Seit Jahren unser Stammlokal — die Qualität bleibt konstant hoch.', author: 'Elisabeth H.' },
    ],
    gallery: [
      { url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80', alt: 'Interior' },
      { url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80', alt: 'Gericht' },
      { url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80', alt: 'Terrasse' },
      { url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80', alt: 'Küche' },
      { url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80', alt: 'Abend' },
      { url: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=800&q=80', alt: 'Wein' },
    ],
    about: { title: 'Unsere Geschichte', body: 'Seit 2008 bringen wir authentische italienische Küche nach Innsbruck. Unsere Zutaten beziehen wir direkt von kleinen Produzenten aus Ligurien und der Toskana.', imageUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=800&q=80' },
  } as any,

  salon: {
    brand: { name: 'Atelier Éclat', tagline: 'Ihr Salon für Styling & Wohlbefinden', logoUrl: '', primaryColor: '#be185d', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 512 987654', email: 'hello@atelier-eclat.at', address: 'Maria-Theresien-Str. 8', city: '6020 Innsbruck', hours: [{ day: 'Di–Fr', time: '09:00–18:00' }, { day: 'Sa', time: '09:00–14:00' }], mapsUrl: '' },
    social: { instagram: '@ateliereclat', facebook: '', whatsapp: '+43512987654', linkedin: '', youtube: '', tiktok: '', x: '', bookingUrl: '' },
    services: [
      { name: 'Waschen, Schneiden, Föhnen', price: '€ 55', duration: '60 min', description: 'Klassischer Haarschnitt mit Beratung' },
      { name: 'Balayage', price: '€ 120', duration: '120 min', description: 'Natürlich fließende Farbverläufe' },
      { name: 'Braut-Styling', price: '€ 180', duration: '90 min', description: 'Ihr perfekter Look für den großen Tag' },
      { name: 'Keratin-Treatment', price: '€ 150', duration: '90 min', description: 'Glanz und Geschmeidigkeit' },
      { name: 'Herrenschnitt', price: '€ 35', duration: '30 min', description: 'Präzisionsschnitt mit Styling' },
      { name: 'Kopfhaut-Behandlung', price: '€ 45', duration: '30 min', description: 'Revitalisierende Pflege' },
    ],
    testimonials: [
      { text: 'Endlich ein Salon der wirklich zuhört. Mein Balayage ist ein Traum!', author: 'Sophie M.' },
      { text: 'Professionell, entspannt und das Ergebnis spricht für sich.', author: 'Lena F.' },
      { text: 'Das beste Team in Innsbruck. Ich komme seit 3 Jahren hierher.', author: 'Nina R.' },
    ],
    gallery: [
      { url: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80', alt: 'Salon' },
      { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80', alt: 'Styling' },
      { url: 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=800&q=80', alt: 'Color' },
      { url: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&w=800&q=80', alt: 'Interior' },
    ],
    team: [
      { name: 'Clara Hochstetter', role: 'Inhaberin & Stylistin', imageUrl: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=400&q=80' },
      { name: 'Marie Lechner', role: 'Color-Expertin', imageUrl: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=400&q=80' },
    ],
    about: { title: 'Das Atelier', body: 'Gegründet 2016, verbindet Atelier Éclat modernes Hairstyling mit entspannter Atmosphäre. Wir setzen auf nachhaltige Produkte und individuelle Beratung.', imageUrl: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=800&q=80' },
  } as any,

  tradesman: {
    brand: { name: 'Gruber & Söhne', tagline: 'Meisterbetrieb für Sanitär & Heizung', logoUrl: '', primaryColor: '#1d4ed8', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 512 334455', email: 'office@gruber-soehne.at', address: 'Gewerbezone West 4', city: '6020 Innsbruck', hours: [{ day: 'Mo–Fr', time: '07:00–17:00' }, { day: 'Notdienst', time: '24/7 erreichbar' }], mapsUrl: '' },
    social: { instagram: '', facebook: '', whatsapp: '+43512334455', linkedin: '', youtube: '', tiktok: '', x: '' },
    services: [
      { name: 'Heizungsinstallation', description: 'Fußbodenheizung, Radiatoren, Wärmepumpen' },
      { name: 'Sanitär-Neuinstallation', description: 'Bäder, Küchen, Wasseranschlüsse' },
      { name: 'Rohrbruch-Notdienst', description: '24/7 erreichbar, Anfahrt in 30 Minuten' },
      { name: 'Badezimmer-Sanierung', description: 'Von der Planung bis zur Fertigstellung' },
      { name: 'Wartung & Service', description: 'Jährliche Heizungswartung, Entkalkung' },
      { name: 'Energieberatung', description: 'Förderungen, Umstieg auf erneuerbare Energie' },
    ],
    testimonials: [
      { text: 'Sind in 25 Minuten gekommen als unser Rohr geplatzt ist. Absolut zuverlässig!', author: 'Familie Hofer' },
      { text: 'Top Arbeit bei unserer Badsanierung. Sauber, pünktlich und fair im Preis.', author: 'K. Maier' },
      { text: 'Seit 2015 machen sie unsere Heizungswartung. Immer professionell.', author: 'Hausverwaltung Tirol Mitte' },
    ],
    gallery: [
      { url: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=800&q=80', alt: 'Arbeit' },
      { url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=800&q=80', alt: 'Bad' },
      { url: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80', alt: 'Heizung' },
    ],
    about: { title: 'Über uns', body: 'Seit 1998 sind wir als Familienbetrieb in Innsbruck und Umgebung tätig. Drei Generationen Erfahrung in Sanitär, Heizung und Klimatechnik.', imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80' },
  } as any,

  hochzeit: {
    brand: { name: 'Anna & Lukas', tagline: 'Wir heiraten! · 13. September 2026', logoUrl: '', primaryColor: '#92400e', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 664 1234567', email: 'anna.lukas@example.com', address: 'Schloss Ambras', city: '6020 Innsbruck', hours: [{ day: 'Hochzeitsdatum', time: '2026-09-13' }], mapsUrl: 'https://maps.google.com/?q=Schloss+Ambras+Innsbruck' },
    social: { instagram: '', facebook: '', whatsapp: '+436641234567', linkedin: '', youtube: '', tiktok: '', x: '' },
    services: [
      { name: 'Trauung', price: '14:00', description: 'Standesamtliche Trauung im Spanischen Saal' },
      { name: 'Sektempfang', price: '15:00', description: 'Im Schlossgarten mit Canapés' },
      { name: 'Dinner', price: '17:30', description: '4-Gänge-Menü im Festsaal' },
      { name: 'Tortenanschnitt', price: '19:30', description: 'Hochzeitstorte von Bäckerei Rainer' },
      { name: 'Tanz & Party', price: '20:00', description: 'Live-Band bis Mitternacht' },
      { name: 'Late-Night Snack', price: '23:00', description: 'Burger-Bar & Dessert-Buffet' },
    ],
    testimonials: [],
    gallery: [
      { url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80', alt: 'Ringe' },
      { url: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=800&q=80', alt: 'Feier' },
      { url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80', alt: 'Paar' },
      { url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80', alt: 'Location' },
    ],
    about: { title: 'Unsere Geschichte', body: 'Kennengelernt haben wir uns 2019 beim Wandern am Patscherkofel. Drei Gipfel, zwei Hunde und ein gemeinsames Zuhause später – jetzt wird gefeiert!', imageUrl: '' },
  } as any,
};

/** Industry-specific demo content for showcase previews */
export const INDUSTRY_DEMO: Record<string, SiteContent & Record<string, any>> = {
  hotel: {
    brand: { name: 'Bergblick Hotel', tagline: 'Ihr alpines Refugium auf 1.200m', logoUrl: '', primaryColor: '#1e3a5f', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 512 667788', email: 'info@bergblick.at', address: 'Bergweg 24', city: '6166 Fulpmes', hours: [{ day: 'Rezeption', time: '06:00–22:00' }], mapsUrl: '' },
    social: { instagram: '@bergblickhotel', facebook: '', whatsapp: '', linkedin: '', youtube: '', tiktok: '', x: '' },
    services: [
      { name: 'Doppelzimmer Alpin', price: 'ab € 140/Nacht', description: 'Bergblick, Balkon, 28m²' },
      { name: 'Suite Panorama', price: 'ab € 220/Nacht', description: 'Freistehende Wanne, 45m²' },
      { name: 'Familienzimmer', price: 'ab € 180/Nacht', description: '2 Räume, Kinderbett, 38m²' },
      { name: 'Frühstücksbuffet', price: 'inkl.', description: 'Regional & Bio, 07:00–10:00' },
      { name: 'Spa & Sauna', price: 'inkl.', description: 'Finnische Sauna, Dampfbad, Pool' },
      { name: 'E-Bike Verleih', price: '€ 35/Tag', description: 'Geführte Touren auf Anfrage' },
    ],
    testimonials: [{ text: 'Die beste Aussicht und das freundlichste Team.', author: 'M. Berger' }, { text: 'Perfekt für Familien — wir kommen jedes Jahr.', author: 'Familie Steiner' }],
    gallery: [{ url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80', alt: 'Hotel' }],
    about: { title: 'Das Hotel', body: 'Seit 1985 empfangen wir Gäste im Stubaital. Familiär geführt, authentisch alpin.', imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80' },
  } as any,
  cafe: {
    brand: { name: 'Kaffeewerk', tagline: 'Specialty Coffee & Hausgemachtes', logoUrl: '', primaryColor: '#78350f', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 512 112233', email: 'hi@kaffeewerk.at', address: 'Universitätsstr. 3', city: '6020 Innsbruck', hours: [{ day: 'Mo–Fr', time: '07:30–18:00' }, { day: 'Sa–So', time: '09:00–17:00' }], mapsUrl: '' },
    social: { instagram: '@kaffeewerk_ibk', facebook: '', whatsapp: '', linkedin: '', youtube: '', tiktok: '', x: '' },
    services: [
      { name: 'Flat White', price: '€ 4.20', description: 'Double Shot, Hafermilch verfügbar' },
      { name: 'Avocado Toast', price: '€ 9.50', description: 'Sauerteig, pochiertes Ei, Microgreens' },
      { name: 'Banana Bread', price: '€ 4.80', description: 'Vegan, mit Walnüssen' },
      { name: 'Matcha Latte', price: '€ 5.00', description: 'Bio-Matcha aus Kyoto' },
      { name: 'Frühstücksbowl', price: '€ 11.50', description: 'Granola, Beeren, Joghurt' },
    ],
    testimonials: [{ text: 'Der beste Kaffee in Innsbruck, Punkt.', author: 'Alex R.' }],
    gallery: [{ url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80', alt: 'Café' }],
    about: { title: 'Das Kaffeewerk', body: 'Seit 2019 rösten wir unsere Bohnen selbst und servieren sie mit Liebe zum Detail.', imageUrl: '' },
  } as any,
  arzt: {
    brand: { name: 'Dr. Kauer & Team', tagline: 'Ihre Hausarztpraxis in Innsbruck', logoUrl: '', primaryColor: '#0e7490', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 512 556677', email: 'praxis@dr-kauer.at', address: 'Anichstraße 20', city: '6020 Innsbruck', hours: [{ day: 'Mo, Mi, Fr', time: '08:00–12:00' }, { day: 'Di, Do', time: '14:00–18:00' }], mapsUrl: '' },
    social: { instagram: '', facebook: '', whatsapp: '', linkedin: '', youtube: '', tiktok: '', x: '', bookingUrl: '' },
    services: [
      { name: 'Allgemeinmedizin', description: 'Vorsorge, Akutbehandlung, Überweisungen' },
      { name: 'Gesunden-Untersuchung', description: 'Jährliche Vorsorge, alle Kassen' },
      { name: 'EKG & Belastungstest', description: 'Herzfunktionsdiagnostik' },
      { name: 'Impfberatung', description: 'Reise- und Standardimpfungen' },
      { name: 'Labordiagnostik', description: 'Blutbild, Schilddrüse, Vitamine' },
      { name: 'Wundversorgung', description: 'Kleinchirurgische Eingriffe' },
    ],
    testimonials: [{ text: 'Endlich ein Arzt der sich Zeit nimmt und verständlich erklärt.', author: 'P. Müller' }],
    gallery: [{ url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80', alt: 'Praxis' }],
    about: { title: 'Die Praxis', body: 'Seit 2012 betreuen wir Patientinnen und Patienten aller Altersgruppen im Herzen von Innsbruck.', imageUrl: '' },
  } as any,
  anwalt: {
    brand: { name: 'Kanzlei Reiter', tagline: 'Recht klar. Kompetent. Persönlich.', logoUrl: '', primaryColor: '#1e293b', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 512 998877', email: 'office@kanzlei-reiter.at', address: 'Maximilianstraße 2', city: '6020 Innsbruck', hours: [{ day: 'Mo–Do', time: '09:00–17:00' }, { day: 'Fr', time: '09:00–13:00' }], mapsUrl: '' },
    social: { instagram: '', facebook: '', whatsapp: '', linkedin: '', youtube: '', tiktok: '', x: '' },
    services: [
      { name: 'Arbeitsrecht', description: 'Kündigung, Abfindung, Verträge' },
      { name: 'Mietrecht', description: 'Mängel, Kautionsstreit, Räumung' },
      { name: 'Familienrecht', description: 'Scheidung, Sorgerecht, Unterhalt' },
      { name: 'Vertragsrecht', description: 'Prüfung, Gestaltung, Durchsetzung' },
      { name: 'Erbrecht', description: 'Testament, Pflichtteil, Nachlassverfahren' },
    ],
    testimonials: [{ text: 'Herr Reiter hat meinen Fall ruhig und souverän gelöst.', author: 'Anonym' }],
    gallery: [],
    about: { title: 'Die Kanzlei', body: 'Seit 2005 vertreten wir Privatpersonen und kleine Unternehmen in Tirol mit Engagement und Klarheit.', imageUrl: '' },
  } as any,
  immobilien: {
    brand: { name: 'Alpstein Immobilien', tagline: 'Ihr Partner für Wohn- und Anlageimmobilien', logoUrl: '', primaryColor: '#065f46', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 512 443322', email: 'info@alpstein-immo.at', address: 'Südtiroler Platz 1', city: '6020 Innsbruck', hours: [{ day: 'Mo–Fr', time: '09:00–17:00' }], mapsUrl: '' },
    social: { instagram: '@alpstein_immo', facebook: '', whatsapp: '+43512443322', linkedin: '', youtube: '', tiktok: '', x: '' },
    services: [
      { name: '3-Zi Altbau Saggen', price: '€ 385.000', description: '78m², Balkon, renoviert 2023' },
      { name: 'Penthouse Wilten', price: '€ 720.000', description: '120m², Dachterrasse, Bergblick' },
      { name: 'Garconniere Pradl', price: '€ 195.000', description: '35m², vermietet, 3,8% Rendite' },
      { name: 'Einfamilienhaus Rum', price: '€ 850.000', description: '180m², Garten 400m², Garage' },
    ],
    testimonials: [{ text: 'Hat unsere Wohnung in 3 Wochen verkauft — zum Wunschpreis.', author: 'H. Schwarz' }],
    gallery: [{ url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80', alt: 'Objekt' }],
    about: { title: 'Über uns', body: 'Seit 2010 vermitteln wir Immobilien in Innsbruck und Umgebung. Lokal verwurzelt, marktgerecht bewertet.', imageUrl: '' },
  } as any,
  fotograf: {
    brand: { name: 'Lena Berger Photography', tagline: 'Momente die bleiben', logoUrl: '', primaryColor: '#4c1d95', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 664 5556677', email: 'hello@lenaberger.at', address: '', city: 'Innsbruck & Umgebung', hours: [{ day: 'Buchungsanfrage', time: 'jederzeit per Mail' }], mapsUrl: '' },
    social: { instagram: '@lenaberger.photo', facebook: '', whatsapp: '+436645556677', linkedin: '', youtube: '', tiktok: '', x: '' },
    services: [
      { name: 'Hochzeitspaket Classic', price: 'ab € 2.400', description: '8h Begleitung, 400+ editierte Bilder' },
      { name: 'Portrait-Session', price: '€ 290', description: '1h Shooting, 20 editierte Bilder' },
      { name: 'Business-Portraits', price: '€ 450', description: 'Team- und Einzelportraits, LinkedIn-ready' },
      { name: 'Event-Dokumentation', price: 'ab € 800', description: 'Firmenevents, Galas, Konferenzen' },
    ],
    testimonials: [{ text: 'Lena hat unsere Hochzeit magisch eingefangen.', author: 'Anna & Lukas' }],
    gallery: [
      { url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80', alt: 'Wedding' },
      { url: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=800&q=80', alt: 'Portrait' },
    ],
    about: { title: 'Über mich', body: 'Seit 2017 dokumentiere ich Lebensmomente — authentisch, natürlich und mit einem Auge für Licht.', imageUrl: '' },
  } as any,
  fitness: {
    brand: { name: 'PEAK Gym', tagline: 'Train hard. Recover smart.', logoUrl: '', primaryColor: '#dc2626', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 512 778899', email: 'info@peakgym.at', address: 'Industriestraße 12', city: '6020 Innsbruck', hours: [{ day: 'Mo–Fr', time: '06:00–22:00' }, { day: 'Sa–So', time: '08:00–20:00' }], mapsUrl: '' },
    social: { instagram: '@peakgym_ibk', facebook: '', whatsapp: '', linkedin: '', youtube: '', tiktok: '', x: '' },
    services: [
      { name: 'Basic Membership', price: '€ 39/Monat', description: 'Freihantel, Geräte, Cardio' },
      { name: 'Premium', price: '€ 59/Monat', description: '+ Kurse, Sauna, Towel-Service' },
      { name: 'Personal Training', price: '€ 75/Session', description: '1:1 mit zertifiziertem Trainer' },
      { name: 'CrossFit Box', price: '€ 89/Monat', description: 'Unlimited WODs, Community' },
      { name: 'Yoga Flow', price: 'inkl. Premium', description: 'Di & Do 18:00, 60 min' },
    ],
    testimonials: [{ text: 'Bestes Gym in Innsbruck. Sauber, modern und super Trainer.', author: 'Max P.' }],
    gallery: [{ url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80', alt: 'Gym' }],
    about: { title: 'PEAK Gym', body: 'Seit 2020 — 1.500m² Training auf höchstem Niveau mitten in Innsbruck.', imageUrl: '' },
  } as any,
  'event-location': {
    brand: { name: 'Loft Eins', tagline: 'Ihr Event. Unser Raum.', logoUrl: '', primaryColor: '#7c3aed', hideName: false, themePresetId: '', customThemes: [] },
    contact: { phone: '+43 512 445566', email: 'events@loft-eins.at', address: 'Viaduktbogen 8', city: '6020 Innsbruck', hours: [{ day: 'Anfragen', time: 'Mo–Fr 09:00–17:00' }], mapsUrl: '' },
    social: { instagram: '@lofteins', facebook: '', whatsapp: '', linkedin: '', youtube: '', tiktok: '', x: '' },
    services: [
      { name: 'Loft (200m²)', price: 'ab € 1.800', description: 'Bis 120 Personen, Industriecharme' },
      { name: 'Studio (80m²)', price: 'ab € 800', description: 'Bis 40 Personen, Tageslicht-Raum' },
      { name: 'Dachterrasse', price: 'ab € 600', description: 'Zusatzoption, Mai–September' },
      { name: 'Catering Basis', price: '€ 45/Person', description: 'Buffet, Getränke-Flatrate 4h' },
      { name: 'Technik-Paket', price: '€ 400', description: 'PA, Licht, Mikro, Beamer' },
    ],
    testimonials: [{ text: 'Der perfekte Raum für unsere Firmenfeier. Alles aus einer Hand.', author: 'M. Brunner, CEO' }],
    gallery: [{ url: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=800&q=80', alt: 'Loft' }],
    about: { title: 'Loft Eins', body: 'Industrial-Chic trifft auf Full-Service. Seit 2018 Innsbrucks beliebteste Event-Location.', imageUrl: '' },
  } as any,
};
