import type { SiteContent, TemplateKey } from './types.js';

const DEMO_NEWS_RESTAURANT: NonNullable<SiteContent['posts']> = [
  {
    id: 'demo-news-restaurant-1',
    title: 'Saisonkarte überarbeitet',
    slug: 'saisonkarte-update',
    date: '2025-04-12',
    excerpt: 'Neue Gerichte mit Spargel, Bärlauch und regionalem Fisch.',
    body: 'Die Küche hat die Frühlingskarte neu geplant.\n\nVon leichten Vorspeisen bis zu den Klassikern — alles frisch.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1551218808-94e220e1d168?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-restaurant-2',
    title: 'Öffnungszeiten an Feiertagen',
    slug: 'feiertage-2025',
    date: '2025-03-20',
    excerpt: 'So haben wir für Sie geöffnet — Reservierung empfohlen.',
    body: 'An den kommenden Feiertagen gelten leicht geänderte Zeiten.\n\nBitte reservieren Sie rechtzeitig.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-restaurant-3',
    title: 'Weinabende im Mai',
    slug: 'weinabende-mai',
    date: '2025-03-01',
    excerpt: 'Jeden Freitag ein anderer Winzer — degustieren und bestellen.',
    body: 'Ab Anfang Mai laden wir jeden Freitag Gastwinzer:innen ein.\n\nPlätze sind limitiert.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
];

const DEMO_NEWS_SALON: NonNullable<SiteContent['posts']> = [
  {
    id: 'demo-news-salon-1',
    title: 'Colour Day: Balayage & Toner',
    slug: 'colour-day-balayage',
    date: '2025-04-08',
    excerpt: 'Education-Team aus Amsterdam — Live-Demos am Samstag.',
    body: 'Wir zeigen neue Verlaufstechniken und Pflege-Routinen für coloriertes Haar.\n\nTermine für Model-Slots über die Rezeption.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-salon-2',
    title: 'Bridal-Styling: Frühlingstermine',
    slug: 'bridal-styling-fruehjahr',
    date: '2025-03-18',
    excerpt: 'Probe-Frisur + Make-up-Paket — limitierte Slots Mai & Juni.',
    body: 'Unser Bridal-Team blockt bewusst weniger Hochzeiten pro Wochenende, damit ihr entspannt startet.\n\nJetzt Probeslot sichern.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-salon-3',
    title: 'Olaplex Intensiv-Woche',
    slug: 'olaplex-intensiv-woche',
    date: '2025-02-22',
    excerpt: 'Struktur-Aufbau-Kur inkl. Haar-Analyse — nur diese Woche.',
    body: 'Wir kombinieren Salon-Ritual mit Zuhause-Pflegeplan.\n\nIdeal nach Winter & Mützen-Saison.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
];

const DEMO_NEWS_TRADESMAN: NonNullable<SiteContent['posts']> = [
  {
    id: 'demo-news-tradesman-1',
    title: 'BAFA & KfW: Was sich 2025 ändert',
    slug: 'bafa-kfw-2025',
    date: '2025-04-05',
    excerpt: 'Heizung, Solar, Lüftung — welche Anträge jetzt Sinn machen.',
    body: 'Wir fassen die wichtigsten Fristen und Kombinationen für Sanierung & Neubau zusammen.\n\nKurzberatung telefonisch möglich.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-tradesman-2',
    title: 'Notdienst Ostern & Maifeiertage',
    slug: 'notdienst-feiertage',
    date: '2025-03-12',
    excerpt: 'Rufbereitschaft Heizung & Rohr — Reaktionszeiten & Gebühren.',
    body: 'Unser Meisterbetrieb teilt die Bereitschaft mit der Partner-Innung.\n\nBitte Notfallnummer speichern.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-tradesman-3',
    title: 'Festpreis-Garantie bei Bad-Sanierung',
    slug: 'festpreis-bad-sanierung',
    date: '2025-02-28',
    excerpt: 'Leistungsverzeichnis + Puffer — keine Überraschungen bei Abnahme.',
    body: 'Transparente Kalkulation mit Meilensteinen.\n\nVor-Ort-Termin innerhalb von 5 Werktagen.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
];

const DEMO_NEWS_HOTEL: NonNullable<SiteContent['posts']> = [
  {
    id: 'demo-news-hotel-1',
    title: 'Frühling am Berg: 3=2 Pakete',
    slug: 'fruehling-drei-zwei',
    date: '2025-04-10',
    excerpt: 'Mai & Juni — inkl. Spa-Zugang & Gipfelshuttle.',
    body: 'Direktbucher profitieren von flexiblen Stornobedingungen.\n\nFamilienzimmer sind begrenzt.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-hotel-2',
    title: 'Spa-Neuigkeiten: Sauna-Aufgüsse',
    slug: 'spa-aufguesse-mai',
    date: '2025-03-25',
    excerpt: 'Kräuter aus dem Hotelgarten — ab Mai dienstags & donnerstags.',
    body: 'Unsere Spa-Managerin stellt die neue Ritual-Reihe vor.\n\nHotelgäste: kostenfrei, externe Gäste: Day-Spa-Ticket.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-hotel-3',
    title: 'Kulinarik: Supper Club im Keller',
    slug: 'supper-club-keller',
    date: '2025-03-01',
    excerpt: 'Degustation mit Weinpaket — 14 Gänge, kleine Tische.',
    body: 'Einmal im Monat öffnet unser Weinkeller für ein intimes Dinner.\n\nReservierung nur über die Rezeption.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
];

const DEMO_NEWS_TOURISM: NonNullable<SiteContent['posts']> = [
  {
    id: 'demo-news-tourism-1',
    title: 'Neue Gipfeltour: drei Gletscher in einem Tag',
    slug: 'gipfeltour-drei-gletscher',
    date: '2025-04-14',
    excerpt: 'Kleine Gruppe, UIAGM-Guide, Seilbahn-Logistik inklusive.',
    body: 'Für erfahrene Bergsteiger:innen mit Trittsicherheit und Ausdauer.\n\nMaterial-Check am Vorabend.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-tourism-2',
    title: 'Private Guides & Corporate Retreats',
    slug: 'private-guides-retreats',
    date: '2025-03-19',
    excerpt: 'Programme auf Englisch & Deutsch — Halb- oder Ganztage.',
    body: 'Wir planen Routen entlang Wasser, Wald oder Gipfel — inklusive Picknick.\n\nFrüh buchen für Sommer.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-tourism-3',
    title: 'Lawinenkunde: Termine März & April',
    slug: 'lawinenkunde-termine',
    date: '2025-02-26',
    excerpt: 'Theorie + Praxis am Übungshang — ABS-Probe möglich.',
    body: 'Offen für Skitourengeher:innen und Splitboarder.\n\nMax. 8 Personen pro Kurs.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
];

const DEMO_NEWS_CONSULTING: NonNullable<SiteContent['posts']> = [
  {
    id: 'demo-news-consulting-1',
    title: 'Steuerliche Eckpunkte 2026 für KMU',
    slug: 'steuer-eckpunkte-2026',
    date: '2025-04-09',
    excerpt: 'Abschreibungen, Mindestlohn, Umsatzsteuer — was Mandanten jetzt prüfen sollten.',
    body: 'Kurzüberblick für Geschäftsführer:innen und Finanzverantwortliche.\n\nAusführlicher Mandanten-Newsletter folgt.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-consulting-2',
    title: 'Unternehmensnachfolge: fünf häufige Fallen',
    slug: 'nachfolge-fuenf-fallen',
    date: '2025-03-21',
    excerpt: 'Bewertung, Steuern, Gesellschaftsform — aus der Praxis unserer Kanzlei.',
    body: 'Wir zeigen, wo Familienunternehmen Zeit verlieren — und wie man es strukturiert angeht.\n\nErstgespräch nach Termin.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-consulting-3',
    title: 'CSRD & ESG: pragmatische Checkliste',
    slug: 'csrd-esg-checkliste',
    date: '2025-02-27',
    excerpt: 'Was Mittelständler jetzt dokumentieren sollten — ohne „Compliance-Theater“.',
    body: 'Fokus auf Datenqualität und Lieferketten-Risiken.\n\nWorkshop-Termine in München & Wien.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
];

const DEMO_NEWS_MEDICAL: NonNullable<SiteContent['posts']> = [
  {
    id: 'demo-news-medical-1',
    title: 'Impfaktion Frühjahr: Grippe & Tdap',
    slug: 'impfaktion-fruehjahr',
    date: '2025-04-06',
    excerpt: 'Termine online — kurze Wartezeiten, alle Kassen.',
    body: 'Bitte Impfpass mitbringen.\n\nAkutsprechstunde läuft parallel.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-medical-2',
    title: 'Check-up 35+: was die Kasse übernimmt',
    slug: 'checkup-35-kasse',
    date: '2025-03-14',
    excerpt: 'Vorsorge-Untersuchung Schritt für Schritt erklärt.',
    body: 'Labor, EKG, Beratung — wir bündeln alles in einem Terminblock.\n\nFragen vorab per Mail möglich.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-medical-3',
    title: 'Telemedizin in unserer Praxis',
    slug: 'telemedizin-praxis',
    date: '2025-02-20',
    excerpt: 'Folgerezepte & Befundgespräche — sicher über die Patienten-App.',
    body: 'Akute Beschwerden weiterhin vor Ort.\n\nDatenschutz nach DSGVO.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
];

const DEMO_NEWS_FITNESS: NonNullable<SiteContent['posts']> = [
  {
    id: 'demo-news-fitness-1',
    title: 'Open Gym: neue Frühzeiten',
    slug: 'open-gym-fruehzeiten',
    date: '2025-04-11',
    excerpt: 'Ab 06:00 — Zugang per App, kein Check-in an der Theke.',
    body: 'Wir erweitern die Slots für Schichtarbeiter:innen.\n\nPersonal Trainer auf Anfrage.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-fitness-2',
    title: 'HYROX-Prep-Kurs startet Mai',
    slug: 'hyrox-prep-mai',
    date: '2025-03-17',
    excerpt: 'Lauf + Functional — 8 Wochen, begrenzte Plätze.',
    body: 'Technik-Schwerpunkte SkiErg, Sled, Burpees.\n\nProbetraining am Open Saturday.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
  {
    id: 'demo-news-fitness-3',
    title: 'Ernährungscoaching: Gruppenstart Juni',
    slug: 'ernaehrung-gruppe-juni',
    date: '2025-02-25',
    excerpt: 'Alltagstauglich, ohne Crash-Diät — mit Labor-Optional.',
    body: 'Wöchentliche Check-ins im Studio + Chat-Support.\n\nMitglieder: 15 % Rabatt.',
    bodyHtml: '',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80',
    published: true,
  },
];

export const DEMO_NEWS_BY_TEMPLATE: Record<TemplateKey, NonNullable<SiteContent['posts']>> = {
  restaurant: DEMO_NEWS_RESTAURANT,
  salon: DEMO_NEWS_SALON,
  tradesman: DEMO_NEWS_TRADESMAN,
  hotel: DEMO_NEWS_HOTEL,
  tourism: DEMO_NEWS_TOURISM,
  consulting: DEMO_NEWS_CONSULTING,
  medical: DEMO_NEWS_MEDICAL,
  fitness: DEMO_NEWS_FITNESS,
};

/** @deprecated Prefer `DEMO_NEWS_BY_TEMPLATE` oder `demoNewsFallbackForTemplate`. */
export const DEMO_NEWS_POSTS = DEMO_NEWS_RESTAURANT;

export function demoNewsFallbackForTemplate(tpl: TemplateKey): NonNullable<SiteContent['posts']> {
  return DEMO_NEWS_BY_TEMPLATE[tpl];
}
